// this file was generated by serverless-auto-swagger
            module.exports = {
  "swagger": "2.0",
  "info": {
    "title": "product-service",
    "version": "1"
  },
  "paths": {
    "/products": {
      "get": {
        "summary": "getProductsList",
        "description": "",
        "operationId": "getProductsList.get.products",
        "consumes": [
          "application/json"
        ],
        "produces": [
          "application/json"
        ],
        "parameters": [],
        "responses": {
          "200": {
            "description": "Success response",
            "schema": {
              "$ref": "#/definitions/Product"
            }
          }
        }
      }
    }
  },
  "definitions": {
    "Products": {
      "properties": {
        "\"count\"": {
          "title": "Products.\"count\"",
          "type": "number"
        },
        "\"id\"": {
          "title": "Products.\"id\"",
          "type": "string"
        },
        "\"description\"": {
          "title": "Products.\"description\"",
          "type": "string"
        },
        "\"title\"": {
          "title": "Products.\"title\"",
          "type": "string"
        },
        "\"price\"": {
          "title": "Products.\"price\"",
          "type": "number"
        }
      },
      "required": [
        "\"count\"",
        "\"id\"",
        "\"description\"",
        "\"title\"",
        "\"price\""
      ],
      "additionalProperties": false,
      "title": "Products",
      "type": "object"
    }
  },
  "securityDefinitions": {}
};